#! /bin/bash

cd ~/.spacetime

query=$1
subject=$2

timeNow=$(cat .current)
timeDay=$(cat $subject/.cycle-day)
timeMonth=$(cat $subject/.cycle-month)
timeYear=$(cat $subject/.cycle-year)

timeHours=$(($timeDay*$timeMonth*$timeYear)) #Number of hours to fully revolve

if [[ "$query" == "angle" ]]; then
	timeIntoYear=$(($timeNow%timeHours))
	echo $timeIntoYear > /tmp/tiy
#	angleAroundSun=$((36000*$timeIntoYear/$timeHours))
	angleAroundSun=$(awk -v A=$timeIntoYear -v B=$timeHours 'BEGIN{print 360*A/B}')
	echo $angleAroundSun
fi

if [[ "$query" == "radius" ]]; then
	mass=$(cat $subject/.star/.mass)
	G="1327000000000000000"
	rad=$(awk -v M=$mass -v G=$G -v P=$timeHours 'BEGIN{print (((G*M*(3600*P)^2)/39)^(1/3)/149597870700)}')
	echo $rad
fi

